language: php
sudo: required
services:
  - rabbitmq
php:
  - '5.5'
  - '7.0'
install:
  - echo | pecl install -f amqp-1.7.0
  - composer self-update
before_script:
  - composer install
  - php -m
script:
  - ./bot.php
  - ./bot.php status